baseURL: "https://beta.theaccessagency.com.au/"
languageCode: "en-us"
title: "The Access Agency"

copyright: "© Copyright 2022 | The Access Agency"

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true

paginate: 12

taxonomies:
  categories: 'categories'
  kategorier: 'kategorier'
permalinks:
  kategorier: "/:slug"

markup:
  markup.goldmark:
    markup.goldmark.renderer:
      unsafe: true

menu:
  navbar:
  - name: Home
    url: "/"
    weight: 10
  - name: Accessible Tourism
    url: "/accessible-tourism/"
    weight: 20
  - name: About Us
    url: "/about-us/"
    weight: 30
  - name: Our Services
    url: "/services/"
    weight: 40
  - name: Work
    url: "/work/"
    weight: 50
  - name: Resources
    url: "/resources/"
    weight: 60
  - name: Contact
    url: "/contact/"
    weight: 70

  social:
  - name: Instagram
    url: "https://www.instagram.com/freewheelweekends/"
    pre: instagram
    weight: 20
  - name: Linkedin
    url: "https://www.linkedin.com/in/ryansmith-au/"
    pre: linkedin
    weight: 30

  footer:
  - name: Home
    url: "/"
    weight: 10
  - name: Accessible Tourism
    url: "/accessible-tourism/"
    weight: 20
  - name: About Us
    url: "/about-us/"
    weight: 30
  - name: Services
    url: "/services/"
    weight: 40
  - name: Work
    url: "/work/"
    weight: 50
  - name: Resources
    url: "/resources/"
    weight: 60
  - name: Contact
    url: "/contact/"
    weight: 70

params:
  description: "The Access Agency – Design, Access and Communications"
  logo_light: "/images/logo-light.svg"
  logo_dark: "/images/logo-dark.svg"
  logo_footer: "/images/logo-mark.svg"
  author: "elHefe"
  github: "#"
  ogimage: "/images/TheAccessAgency_thumbnail.png"
  sitename: "TheAccessAgency"
  twitter: "#"
  email: hello@theaccessagency.com.au
  phone: "#"
  address: Albert Park, Melbourne, Australia
  footer_text: |-
    The Access Agency acknowledges and pays respect to the past, present and future Traditional Custodians and Elders of this nation. We live and work on Wurundjeri and Woiwurrung land and acknowledge the continuation of cultural, spiritual and educational practices of Aboriginal and Torres Strait Islander peoples.

    We're continually working to make our website more accessible, if you have any complaints or comments please send them through to [hello[at]theaccessagency.com.au.](mailto:hello@theaccessagency.com.au)
