baseURL: ""
languageCode: "en-us"
title: "Startup"

copyright: "Lorem ipsum is placeholder text commonly used. Copyright © 2022 All Rights Reserved"

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true

paginate: 2

  

taxonomies:
  categories: 'categories'
  kategorier: 'kategorier'
permalinks:
  kategorier: "/:slug"

markup:
  markup.goldmark:
    markup.goldmark.renderer:
      unsafe: true

menu:
  navbar:
  - name: Services
    url: "#"
    weight: 10
  - name: Product one
    url: "#"
    parent: Services
    pre: code
    weight: 110
  - name: Product two
    url: "#"
    parent: Services
    pre: hashtag
    weight: 120
  - name: Product three
    url: "#"
    parent: Services
    pre: cube-transparent
    weight: 130
  - name: Product four
    url: "#"
    parent: Services
    pre: template
    weight: 140
  - name: Product five
    url: "#"
    parent: Services
    pre: cube-transparent
    params:
      desc: Lorem ipsum
    weight: 150
  - name: Pricing
    url: "#"
    weight: 20
  - name: Blog
    url: "/blog/"
    weight: 30
  - name: Contact
    url: "#"
    weight: 40

  navbar_cta:
  - name: Login
    url: "#"
    pre: secondary
    weight: 10
  - name: Sign up
    url: "#"
    pre: primary
    weight: 20

  social:
  - name: Facebook
    url: "#"
    pre: facebook
    weight: 10
  - name: Instagram
    url: "#"
    pre: instagram
    weight: 20
  - name: Twitter
    url: "#"
    pre: twitter
    weight: 30
  - name: GitHub
    url: "#"
    pre: github
    weight: 40
  - name: Dribbble
    url: "#"
    pre: dribbble
    weight: 50

  footer:
  - name: Services
    weight: 10

  - name: Products
    url: "#"
    parent: Services
    weight: 10
  - name: Work
    url: "#"
    parent: Services
    weight: 20
  - name: Custom
    url: "#"
    parent: Services
    weight: 30

  - name: Company
    weight: 20

  - name: About
    url: "#"
    parent: Company
    weight: 10
  - name: Jobs
    url: "#"
    parent: Company
    weight: 20
  - name: Terms
    url: "#"
    parent: Company
    weight: 30

params:
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
  logo: "/images/logo.svg"
  author: "OfficeGeek"
  github: "#"
  ogimage: "/images/og.png"
  sitename: "OfficeGeek"
  twitter: "#"
  email: support@workcation.com
  phone: +1 555 123-4567
  address: Long street 24, London E16GH, United Kingdom

  banner:
    text: Lorem ipsum is placeholder text commonly used
    button:
      text: Learn More
      url: "#"

  navbar:
  - name: Kurser
    url: "/kurser/"
    children:
    - name: Tailwind CSS
      url: "/tailwindcss/"
      icon: code
    - name: Alpine.js
      url: "/alpinejs/"
      icon: hashtag
    - name: Hugo
      url: "/hugo/"
      icon: cube-transparent
    - name: Design
      url: "/design/"
      icon: template
    - name: Productivity
      url: "/hugo/"
      icon: cube-transparent
    - name: All posts
      url: "/blog/"
      icon: document-duplicate   
  - name: Webinar
    url: "/webinar/"
  - name: En til En
    url: "/en-til-en/"
  - name: Spørgsmål
    url: "/sporgsmal/"
  - name: Blog
    url: "/blog/"
  - name: Om
    url: "/om/"
  - name: Kontakt
    url: "/kontakt/"

  navbar_cta:
    name: Kurser
    url: "#kurser"
  footer_1:
  - name: Kurser
    url: "/kurser/"
  - name: Webinar
    url: "/webinar/"
  - name: En til En
    url: "/en-til-en/"
  - name: Spørgsmål
    url: "/sporgsmal/"
