baseURL: "https://beta.theaccessagency.com.au/"
languageCode: "en-us"
title: "The Access Agency"

copyright: "2022 Copyright Terms and Conditions"

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true

paginate: 2

taxonomies:
  categories: 'categories'
  kategorier: 'kategorier'
permalinks:
  kategorier: "/:slug"

markup:
  markup.goldmark:
    markup.goldmark.renderer:
      unsafe: true

menu:
  navbar:
  - name: Home
    url: "/"
    weight: 5
  - name: Accessible Tourism
    url: "/accessible-tourism/"
    weight: 10
  - name: About + Services
    url: "/about-services/"
    weight: 20
  - name: Work
    url: "/work/"
    weight: 30
  - name: Resources
    url: "/resources/"
    weight: 40
  - name: Freewheel Weekends
    url: "/freewheel-weekends/"
    weight: 60
  - name: Contact
    url: "/contact/"
    weight: 70

  social:
  - name: Instagram
    url: "#"
    pre: instagram
    weight: 20
  - name: Linkedin
    url: "#"
    pre: linkedin
    weight: 30

  footer:
  - name: Home
    url: "/"
    weight: 10
  - name: Accessible Tourism
    url: "/accessible-tourism/"
    weight: 20
  - name: About
    url: "/about/"
    weight: 30
  - name: Services
    url: "/services/"
    weight: 40
  - name: Resources
    url: "/resources/"
    weight: 50
  - name: Work
    url: "/work/"
    weight: 60
  - name: Freewheel Weekends
    url: "/freewheel-weekends/"
    weight: 70
  - name: Contact
    url: "/contact/"
    weight: 80

params:
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
  logo_light: "/images/logo-light.svg"
  logo_dark: "/images/logo-dark.svg"
  logo_footer: "/images/logo-mark.svg"
  author: "OfficeGeek"
  github: "#"
  ogimage: "/images/og.png"
  sitename: "OfficeGeek"
  twitter: "#"
  email: support@workcation.com
  phone: +1 555 123-4567
  address: Long street 24, London E16GH, United Kingdom
  footer_text: |-
    The Access Agency acknowledges and pays respect to the past, present and future Tradi- tional Custodians and Elders of this nation. We live and work on Wurundjeri Woiwurrung land and acknowledge the continuation of cultural, spiritual and educational practices of Aboriginal and Torres Strait Islander peoples.

    We're continually working to make our website more accessible, if you have any complaints or comments please send them through to hello[at]theaccessagency.com.au.
