baseURL: ""
languageCode: "en-us"
title: "The Access Agency"

copyright: "2022 Copyright Terms and Conditions"

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true

paginate: 1

taxonomies:
  categories: 'categories'
  kategorier: 'kategorier'
permalinks:
  kategorier: "/:slug"

markup:
  markup.goldmark:
    markup.goldmark.renderer:
      unsafe: true

menu:
  navbar:
  - name: Accessible Tourism
    url: "/accessible-tourism/"
    weight: 10
  - name: About
    url: "/about/"
    weight: 20
  - name: Services
    url: "/services/"
    weight: 30
  - name: Resources
    url: "/resources/"
    weight: 40
  - name: Work
    url: "/work/"
    weight: 50
  - name: Freewheel Weekends
    url: "/freewheel-weekends/"
    weight: 60
  - name: Contact
    url: "/contact/"
    weight: 70

  social:
  - name: Facebook
    url: "#"
    pre: facebook
    weight: 10
  - name: Instagram
    url: "#"
    pre: instagram
    weight: 20
  - name: Twitter
    url: "#"
    pre: twitter
    weight: 30
  - name: GitHub
    url: "#"
    pre: github
    weight: 40
  - name: Dribbble
    url: "#"
    pre: dribbble
    weight: 50

  footer:
  - name: Home
    url: "/"
    weight: 10
  - name: Accessible Tourism
    url: "/accessible-tourism/"
    weight: 20
  - name: About
    url: "/about/"
    weight: 30
  - name: Services
    url: "/services/"
    weight: 40
  - name: Resources
    url: "/resources/"
    weight: 50
  - name: Work
    url: "/work/"
    weight: 60
  - name: Freewheel Weekends
    url: "/freewheel-weekends/"
    weight: 70
  - name: Contact
    url: "/contact/"
    weight: 80

params:
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
  logo: "/images/logo.svg"
  logo_mark: "/images/logo-mark.svg"
  author: "OfficeGeek"
  github: "#"
  ogimage: "/images/og.png"
  sitename: "OfficeGeek"
  twitter: "#"
  email: support@workcation.com
  phone: +1 555 123-4567
  address: Long street 24, London E16GH, United Kingdom
  footer_text: |-
    The Access Agency acknowledges and pays respect to the past, present and future Tradi- tional Custodians and Elders of this nation. We live and work on Wurundjeri Woiwurrung land and acknowledge the continuation of cultural, spiritual and educational practices of Aboriginal and Torres Strait Islander peoples.
    
    We're continually working to make our website more accessible, if you have any complaints or comments please send them through to hello[at]theaccessagency.com.au.
  

  banner:
    text: Lorem ipsum is placeholder text commonly used
    button:
      text: Learn More
      url: "#"

  navbar:
  - name: Kurser
    url: "/kurser/"
    children:
    - name: Tailwind CSS
      url: "/tailwindcss/"
      icon: code
    - name: Alpine.js
      url: "/alpinejs/"
      icon: hashtag
    - name: Hugo
      url: "/hugo/"
      icon: cube-transparent
    - name: Design
      url: "/design/"
      icon: template
    - name: Productivity
      url: "/hugo/"
      icon: cube-transparent
    - name: All posts
      url: "/blog/"
      icon: document-duplicate   
  - name: Webinar
    url: "/webinar/"
  - name: En til En
    url: "/en-til-en/"
  - name: Spørgsmål
    url: "/sporgsmal/"
  - name: Blog
    url: "/blog/"
  - name: Om
    url: "/om/"
  - name: Kontakt
    url: "/kontakt/"

  navbar_cta:
    name: Kurser
    url: "#kurser"
  footer_1:
  - name: Kurser
    url: "/kurser/"
  - name: Webinar
    url: "/webinar/"
  - name: En til En
    url: "/en-til-en/"
  - name: Spørgsmål
    url: "/sporgsmal/"
